[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "24"
#noinspection EditedTargetSdkVersion
android-targetSdk = "36"
androidx-activity = "1.10.1"
androidx-activityCompose = "1.12.2"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.1"
androidx-core = "1.16.0"
androidx-espresso = "3.6.1"
androidx-lifecycle = "2.9.6"
androidx-testExt = "1.2.1"
composeHotReload = "1.0.0"
composeMultiplatform = "1.10.0"
junit = "4.13.2"
kotlin = "2.3.21"
kotlinx-coroutines = "1.10.2"
ktor = "3.1.3"
logback = "1.5.18"
skainet = "0.26.0"
kotlinxIo = "0.8.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-io-bytestring = { module = "org.jetbrains.kotlinx:kotlinx-io-bytestring", version.ref = "kotlinxIo" }

# SKaiNET
skainet-lang-core = { module = "sk.ainet.core:skainet-lang-core", version.ref = "skainet" }
skainet-lang-models = { module = "sk.ainet.core:skainet-lang-models", version.ref = "skainet" }
skainet-lang-dag = { module = "sk.ainet.core:skainet-lang-dag", version.ref = "skainet" }
skainet-compile-core = { module = "sk.ainet.core:skainet-compile-core", version.ref = "skainet" }
skainet-compile-dag = { module = "sk.ainet.core:skainet-compile-dag", version.ref = "skainet" }
skainet-backend-cpu = { module = "sk.ainet.core:skainet-backend-cpu", version.ref = "skainet" }
skainet-backend-cpu-jvm = { module = "sk.ainet.core:skainet-backend-cpu", version.ref = "skainet" }
skainet-data-api = { module = "sk.ainet.core:skainet-data-api", version.ref = "skainet" }
skainet-data-simple = { module = "sk.ainet.core:skainet-data-basic", version.ref = "skainet" }
skainet-io-core = { module = "sk.ainet.core:skainet-io-core", version.ref = "skainet" }
skainet-io-gguf = { module = "sk.ainet.core:skainet-io-gguf", version.ref = "skainet" }
skainet-io-onnx = { module = "sk.ainet.core:skainet-io-onnx", version.ref = "skainet" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
