name: Build All Projects

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Build all projects
        run: |
          for dir in $(find . -type d -exec test -f {}/build.gradle -a -f {}/gradlew \; -print | grep -v '\./'); do
            echo "Building $dir"
            cd "$dir" || exit 1
            chmod +x gradlew
            ./gradlew build || echo "Build failed for $dir, continuing..."
            cd - || exit 1
          done
